# This is a basic workflow to help you get started with Actions

name: BuildDll

env:
  Sources: Depth16ToYuv.c
  OutFilename: PopDepthToYuv.dll
  LibPathA: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\lib\\x64"
  LibPathB: "D:\\Windows Kits\\10\\Lib\\10.0.18362.0\\um\\x64"
  LibPathC: "D:\\Windows Kits\\10\\Lib\\10.0.18362.0\\ucrt\\x64"
  
on: 
  push:
    branches:
      - master

jobs:
  buildwindows:
    runs-on: windows
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      
    - name: compile
      run: |
          cl %Sources% /Fe%OutFilename% /link /DLL /LIBPATH:%LibPathA% /LIBPATH:%LibPathB% /LIBPATH:%LibPathC%
      shell: cmd
# "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64\cl.exe"
 
    - name: List artifacts
      run: |
        ls .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{env.OutFilename}}
        path: ${{env.OutFilename}}
